# cloudbuild.yaml
steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app', '.']

# Step 2: Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-python-app']

# Step 3: Create or update the deployment using kubectl
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']

# Step 4: Set the image in the deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/my-python-app-deployment', 'my-python-app=gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA']
